### ISSUE TITLE
Public Repository

### ISSUE THREAD

**Issue by BenSto** [InnoZ/innoz-rails#3]
Mir ist gerade aufgefallen, dass das Repository hier public ist. Ich wäre allerdings stark dafür es private zu setzen, vor allem wenn wir jetzt auch den Style hier benutzen wollen etc.

**Comment by 00Bock** [comment]
@kjoscha und ich haben uns entschieden, das Repo öffentlich zu lassen. Wird der stand für Projektarbeiten übernommen, können die Repos privat (Industrieprojekte) oder öffentlich (Förderprojekte mit open source Anforderung) gehalten werden.

**Comment by BenSto** [comment]
> @kjoscha und ich haben uns entschieden, das Repo öffentlich zu lassen

Jo mir auch relativ egal.
Es geht nur darum, dass wir Probleme kriegen könnten, wenn hier das REEN Design öffentlich zugänglich gemacht wird, wo wir aber eine Lizenz für haben...

**Comment by 00Bock** [comment]
Die offene Frage zu den Html-Dateien bleibt aber schon noch...

**Comment by BenSto** [comment]
Ja die müsst ihr beantworten, ich wollte lediglich den Hinweis geben.
